spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
  mail:
    host: ***REMOVED***
    port: 587
    username: ***REMOVED***
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

cloud:
  S3_ACCESS_KEY_ID:
  S3_SECRET_ACESS_KEY:
  S3_BUCKET:
  aws:
    credentials:
      accessKey: ***REMOVED***
      secretKey: ***REMOVED***
    s3:
      bucket: ***REMOVED***
      dir: /
    region:
      static: ***REMOVED***
    stack:
      auto: false

springdoc:
  packages-to-scan: io.itmca.lifepuzzle.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: demo-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
#  api-docs:
#    path: /api-docs/json
#    groups:
#      enabled: true
  cache:
    disabled: true
  group-configs:
    - group: story
      paths-to-match: /story/**, /stories/**
    - group: auth
      paths-to-match: /auth/**
    - group: user
      paths-to-match: /user/**, /users/**
    - group: question
      paths-to-match: /question/**
    - group: hero
      paths-to-match: /hero/**, /heroes/**