spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  #    hibernate:
  #      ddl-auto: validate
  mail:
    host: ***REMOVED***
    port: 587
    username: ***REMOVED***
    password: ***REMOVED***
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  cloud:
    aws:
      credentials:
        accessKey: ***REMOVED***
        secretKey: ***REMOVED***
      s3:
        bucket: ***REMOVED***
        dir: /
      region:
        static: ***REMOVED***
      stack:
        auto: false
    deepgram:
      credentials:
        acessKey: ***REMOVED***

springdoc:
  packages-to-scan: io.itmca.lifepuzzle.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true
  group-configs:
    - group: 이야기
      paths-to-match: /story/**, /stories/**
    - group: 권한
      paths-to-match: /auth/**
    - group: 유저
      paths-to-match: /user/**, /users/**
    - group: 질문
      paths-to-match: /question/**, /questions/**
    - group: 주인공
      paths-to-match: /hero/**, /heroes/**

sentry:
  dsn: ***REMOVED***
  enable-tracing: true
  logging:
    enabled: true
    minimum-event-level: warn
    minimum-breadcrumb-level: info

slack:
  webhook-url: ***REMOVED***

api:
  chat-gpt:
    uri: ***REMOVED***
    key: ***REMOVED***
  deepgram:
    uri: ***REMOVED***
    key: ***REMOVED***