# Production values for lifepuzzle-image-resizer

replicaCount: 1

image:
  repository: ghcr.io/itmca/lifepuzzle-image-resizer
  pullPolicy: Always
  tag: "latest"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Production environment variables
env:
  LOG_LEVEL: "info"
  WORKER_COUNT: "8"

# Health check configuration for production
healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 45
  periodSeconds: 15
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 5

# Pod security context for production
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

securityContext:
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  seccompProfile:
    type: RuntimeDefault

# Production secrets - will be set via Helm install command
secrets:
  dbPassword: ""
  rabbitmqPassword: ""
  awsAccessKey: ""
  awsSecretKey: ""
  awsS3Bucket: ""

# Production monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
  prometheusRule:
    enabled: true