name: Deploy to Production (lifepuzzle-api)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        env: ${{ secrets }}

      - name: Get current time
        uses: josStorer/get-current-time@v2.1.2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Set artifact
        run: echo "artifact=$(ls ./build/libs/*.jar)" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./services/lifepuzzle-api/Dockerfile
          push: true
          build-args: |
            DB_PROD_URL=${{ secrets.DB_PROD_URL }}
            DB_PROD_USERNAME=${{ secrets.DB_PROD_USERNAME }}
            DB_PROD_PASSWORD=${{ secrets.DB_PROD_PASSWORD }}
            MAIL_HOST=${{ secrets.MAIL_HOST }}
            MAIL_PORT=${{ secrets.MAIL_PORT }}
            MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}
            MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}
            AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            DEEPGRAM_ACCESS_KEY=${{ secrets.DEEPGRAM_ACCESS_KEY }}
            SENTRY_DSN=${{ secrets.SENTRY_DSN }}
            SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
            OPENAI_API_URI=${{ secrets.OPENAI_API_URI }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            DEEPGRAM_API_URI=${{ secrets.DEEPGRAM_API_URI }}
            DEEPGRAM_API_KEY=${{ secrets.DEEPGRAM_API_KEY }}
            APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}
            APPLE_BUNDLE_ID=${{ secrets.APPLE_BUNDLE_ID }}
            APPLE_PRIVATE_KEY_ID=${{ secrets.APPLE_PRIVATE_KEY_ID }}
            APPLE_PRIVATE_KEY=${{ secrets.APPLE_PRIVATE_KEY }}
          tags: ${{ secrets.GHCR_LIFEPUZZLE_API }}:latest

      - name: SSH into Home Server and Restart Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOME_SERVER_HOST }}
          username: ${{ secrets.HOME_SERVER_USER }}
          key: ${{ secrets.HOME_SERVER_SSH_KEY }}
          port: ${{ secrets.HOME_SERVER_PORT }}
          script: |
            echo "Restarting deployment..."
            /opt/homebrew/bin/kubectl config use-context prod-app
            /opt/homebrew/bin/kubectl rollout restart deployment/lifepuzzle
            /opt/homebrew/bin/kubectl rollout status deployment/lifepuzzle